### ISSUE TITLE
Tests needed: 3.1.3 Constraints Document

### ISSUE THREAD

**Issue by awoods** [fcrepo/Fedora-API-Test-Suite#182]
https://fedora.info/2018/06/25/spec/#constraints-document

**Comment by dbernstein** [comment]
This is another example of an abstract provision of the spec that should be verified in every case where a constrainedBy link is involved.  I don't see how we can test this independently.

**Comment by awoods** [comment]
I would suggest choosing a test scenario that will always result in a constrainedBy response
- ensure that the `Link` header is in the response
- ensure that the URI in the `Link` header is deferenceable. 

The challenge may be in find such a scenario... may using `ldp:contains` as a user triple: https://fedora.info/2018/06/25/spec/#ldpc

**Comment by dbernstein** [comment]
@awoods :  this is covered with the new tests for constraints failures using PATCH. See the latest round of commits to https://github.com/fcrepo/Fedora-API-Test-Suite/pull/216 for details.
