### ISSUE TITLE
Test 3.6-B exists... but no 3.6-A

### ISSUE THREAD

**Issue by awoods** [fcrepo/Fedora-API-Test-Suite#196]
This task is to evaluate if more tests should be added for 3.6.
The end result should be one or more tests for section 3.6, named sequentially.

**Comment by bbpennel** [comment]
I think the missing test is supposed to be verification that interaction models may be changed. I have created a PR that attempts to test this:
https://github.com/fcrepo/Fedora-API-Test-Suite/pull/203
But it doesn't seem like it is supported

**Comment by dbernstein** [comment]
PR #203 has been merged.
