### ISSUE TITLE
All AuthZ tests assume literal agent values

### ISSUE THREAD

**Issue by acoburn** [fcrepo/Fedora-API-Test-Suite#219]
All of the WebACL tests assume that `acl:agent` properties are Literal values. While the Fedora-Commons server supports that, this is a departure from the SOLID WebAC spec (upon which the Fedora AuthZ section is based). The SOLID WebAC spec requires that agents are IRIs (specifically, WebIDs), and any implementation that requires agent IRIs won't work with the AuthZ section of this test suite.

**Comment by awoods** [comment]
Resolved with https://github.com/fcrepo/Fedora-API-Test-Suite/pull/260
