### ISSUE TITLE
Assumptions about AuthZ model with admin and user roles

### ISSUE THREAD

**Issue by zimeon** [fcrepo/Fedora-API-Test-Suite#222]
The (newish) parameters for the test suite `--admin-(user|password)` and `--(user|password)` imply assumption of a particular auth model that is not given by the WAC or the Fedora API specs.

Although I haven't thought through what is needed to test, I think one might need a way to authenticate as the owner of the root resource, and then perhaps as a second another user in order to test granting/denying permissions. While admin and regular users might fulfill these roles, it isn't the same think in a WAC world. Thus, at the very least I think these parameters need new names.

**Comment by awoods** [comment]
Would `owner` and `user` be slightly more appropriate?
https://github.com/solid/web-access-control-spec#possible-future

**Comment by peichman-umd** [comment]
@awoods I feel like the word `owner` already has a specific meaning in security and permissions discussions, and I think it would be best to avoid it here. Perhaps `root` instead? For example, `--root-user fedoraAdmin --root-password fedoraAdmin`

**Comment by escowles** [comment]
👍 to being more generic about the roles expected here — having roles with functional names like `reader` and `writer` would be better than assuming there is an `admin` who can do everything.
