### ISSUE TITLE
Invalid Link header constant

### ISSUE THREAD

**Issue by acoburn** [fcrepo/Fedora-API-Test-Suite#237]
The link header defined here: https://github.com/fcrepo/Fedora-API-Test-Suite/blob/master/src/main/java/org/fcrepo/spec/testsuite/Constants.java#L26

is invalid. Note the repetition of quotes at the end of the line: `...\"\""` => `...\""`

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo/Fedora-API-Test-Suite/pull/248
