### ISSUE TITLE
Provide a summary by requirement in HTML report

### ISSUE THREAD

**Issue by whikloj** [fcrepo/Fedora-API-Test-Suite#265]
It would be beneficial if we could provide a simple summary of the number of tests run and passed/failed by the requirement (MUST, MAY, SHOULD).

This would make it easier for potential adopters to see at a glance how close they are to each set of requirements.

ie.

Requirement | Tests Run | Failures
---|---|--- 
MUST | 100 | 1
SHOULD | 21 | 2
MAY | 10 | 8

**Comment by dbernstein** [comment]
It would also be good to show a Skips column as well as a totals row.
