### ISSUE TITLE
New test: Changing LDPR to an LDPRv

### ISSUE THREAD

**Issue by awoods** [fcrepo/Fedora-API-Test-Suite#278]
A new test should be created that verifies the following:
https://fcrepo.github.io/fcrepo-specification/#resource-versioning

> Implementations may allow a subsequent PUT request with a rel="type" link in the Link header specifying type http://mementoweb.org/ns#OriginalResource to convert an existing LDPR into an LDPRv. If such a conversion from an LDPR to an LDPRv is supported, it must be accompanied by the creation of a version container (LDPCv), as noted above.

**Comment by dbernstein** [comment]
@awoods :  this one is ready to go pending resolution of https://github.com/fcrepo/Fedora-API-Test-Suite/issues/260
