### ISSUE TITLE
New tests: MAY support Direct and Indirect containers

### ISSUE THREAD

**Issue by awoods** [fcrepo/Fedora-API-Test-Suite#279]
New tests for optional Direct and Indirect containers:
https://fcrepo.github.io/fcrepo-specification/#ldpc

> Implementations must support the creation and management of [LDP] Basic Containers, and may support the creation and management of [LDP] Direct and Indirect Containers.

Test 3.1.1-A already exists. Two new tests should be created for verifying if Direct or Indirect containers are supported.

**Comment by dbernstein** [comment]
Resolved by https://github.com/fcrepo/Fedora-API-Test-Suite/pull/287
