### ISSUE TITLE
3.1.2-C/3.1.3-C Default ldp:membershipResource should be self

### ISSUE THREAD

**Issue by bbpennel** [fcrepo/Fedora-API-Test-Suite#322]
Tests 3.1.2-C and 3.1.3-C currently require that Direct and Indirect containers default to setting a ldp:membershipResource with the parent of the newly created container as the object. Based on feedback in https://github.com/fcrepo/fcrepo-specification/issues/407 the default object should be the newly created Direct/Indirect container itself.

**Comment by whikloj** [comment]
Resolved with https://github.com/fcrepo/Fedora-API-Test-Suite/commit/f6172420bff4cad8dc00e49061a1d979e9e51fb7
