### ISSUE TITLE
Section 3 failures are failures

### ISSUE THREAD

**Issue by whikloj** [fcrepo/Fedora-API-Test-Suite#41]
Tests 3.1.1-A through 3.1.1-C report as a failure, but in fact they aren't as long as an implementation of Fedora doesn't allow you to use `ldp:contains` as a membership predicate.

I was confused by this as well and opened an issue on the spec and they are proposing some wording changes. https://github.com/fcrepo/fcrepo-specification/issues/332

But essentially (as I understand it).

If an implementation can keep containment uses of `ldp:contains` separate from membership uses then tests 3.1.1-A through C must pass.

But if you try to make a direct or indirect container using `ldp:contains` as the membership predicate and get a `409 Conflict` error, then tests 3.1.1-A through C can be skipped.

**Comment by ibr-jabrego** [comment]
The following modifications for tests in section 3.1.1 LDP Containers will be done to solve the issue an meet the new API Specification.
https://fcrepo.github.io/fcrepo-specification/#ldpc

3.1.1-A Test if API permits the creation of client-managed containment triples.
"A server that allows client-managed triples with the ldp:contains predicate must be able to keep those client-managed triples separate from server-managed containment triples."

3.1.1-B If the creation of client-managed triples is not permitted it will test for the correct response status code and for the "constraints document" header. It will test for both Direct and Indirect Containers.
"If a server cannot keep these two uses of ldp:contains separate then any request to use ldp:contains as the membership predicate ([LDP] 2) for Direct and Indirect Containers, or as a client-managed property, must be rejected with a 409 (Conflict) and an accompanying constraints document."

3.1.1-C For tests using the prefer header:
1) Create a container with client managed ldp:contains. GET the previously created container with prefer "PreferContainment" header. Check for correct response headers.
2) Create a container with client managed ldp:contains. GET the previously created container with prefer "PreferMembership" header. Check for correct response headers.
3) Create a container with client managed ldp:contains. GET the previously created container with prefer "PreferMinimalContainer" header. Check for correct response headers.

"Implementations that can distinguish containment triples may permit ldp:contains as a membership predicate or client-managed property; such implementations should support Prefer: header values allowing clients to distinguish this data in the representation of an LDPR as defined in [LDP]: http://www.w3.org/ns/ldp#PreferContainment, http://www.w3.org/ns/ldp#PreferMembership, and http://www.w3.org/ns/ldp#PreferMinimalContainer. ([LDP] 5.4.1.4 expansion)"

For test 3.1.1-C:  Can someone provide an example that shows a request to create (POST) a container with the triples corresponding to each of the three types of preferred "ldp:contains" relationships?  I'd also like to see what a correct response should look like, headers and body content, for each of the preferred header types (PreferContainment, PreferMembership, PreferMinimalContainer). That way, I can verify that the tests are sending the correct requests and verifying the correct responses.

**Comment by bbpennel** [comment]
@whikloj the section 3.1.1 tests are passing for me at this point, can this issue be closed?

**Comment by whikloj** [comment]
@bbpennel if you are good with the resolution then I'm fine.
