### ISSUE TITLE
RFC3230 does not require a server to respond with multiple digests

### ISSUE THREAD

**Issue by zimeon** [fcrepo/Fedora-API-Test-Suite#43]
The test https://github.com/fcrepo4-labs/Fedora-API-Test-Suite/blob/38c974bb7a03337975f63a978fcf640c43942d62/src/main/java/com/ibr/fedora/testsuite/HttpGet.java#L206 requests `md5` and `sha1` (which should be `sha` btw, see https://github.com/fcrepo/fcrepo-specification/issues/235) digests with no q values (hence q=1.0 for both). The test passes only if it gets both digests back. 

My reading of [RFC3230](https://tools.ietf.org/html/rfc3230#section-4.3.1):

> If multiple acceptable digest-algorithm values are given, the sender's preferred digest-algorithm is the one (or ones) with the highest qvalue.
> 
> ...
>
> A Digest header field MAY contain multiple instance-digest values.

is that in this condition either or both of the digest requested may be returned. I don't see anything that says that ALL of the preferred digests should be returned (if we want that to be part of the Fedora API then I think we'd have to specify it).

**Comment by awoods** [comment]
Accepting only one `Digest` in this scenario seems legitimate.

**Comment by ibr-jabrego** [comment]
I will make the change to accept one or both of the requested digest. Thanks @zimeon @awoods. The sha1 request will be modified to sha aswell.

**Comment by dbernstein** [comment]
This one was fixed and merged long ago.
