### ISSUE TITLE
Custom Want-Digest

### ISSUE THREAD

**Issue by ibr-jabrego** [fcrepo/Fedora-API-Test-Suite#46]
The idea was to permit the user to use custom digests when running the testing. The application would permit the user to add two different paramaters -d1 and -d2. These paramaters would be digests used in the tests which use Want-Digest Headers in GET Requests. If not digests are included when running the application it would use md5 and sha as default. Let me know what you think. Thank you!

**Comment by awoods** [comment]
In an effort to minimize client inputs in running these tests, I would suggest testing `sha`, `sha256`, and `md5`. If any of those algorithms are not supported, the proper error code should be returned.
